name: abo_maged_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.3
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.7
  pinput: ^5.0.0
  flutter_screenutil: ^5.9.3
  flutter_localization: ^0.2.3
  carousel_slider: ^5.0.0
  contained_tab_bar_view: ^0.8.0
  google_maps_flutter: ^2.10.0
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/svgs/countries/ae.svg
    - assets/svgs/countries/eg.svg
    - assets/svgs/countries/iq.svg
    - assets/svgs/countries/jo.svg
    - assets/svgs/countries/kw.svg
    - assets/svgs/countries/ma.svg
    - assets/svgs/countries/om.svg
    - assets/svgs/countries/qa.svg
    - assets/svgs/countries/sa.svg
    - assets/svgs/countries/lb.svg
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
